### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by QuentinRoy** [ametaireau/ireallyhatemoney#8]
In a recent PR (#5), @ametaireau said it would be nice to have an icon.
This icon should be able to be used as a favicon on the browser, but also as an application icon when the application is installed on user's device (e.g. on the dashboard of a Firefox Phone).

Anyway the first step is to create this icon.
Here is a first proposal. The idea is to make the 'H' of hate to look like a currency (color, double stroke). Funny thing is it ends being a '#'.

![irhm-icon](https://cloud.githubusercontent.com/assets/728801/9714753/6043c514-555a-11e5-80b8-043708cd618d.png)
![irhm-icon-2](https://cloud.githubusercontent.com/assets/728801/9715092/71e6c2c8-555d-11e5-87c5-1cd54b75202a.png)

Now that it is done, I am not sure why I tilted the 2 strokes of the 'H'.

**Comment by almet** [comment]
Nice! What would it look like if you reduce the space in between the two strokes?

**Comment by QuentinRoy** [comment]
Close enough? Much better like this anyway.
![irhm-icon-3](https://cloud.githubusercontent.com/assets/728801/9717306/f356083c-5571-11e5-8543-a5487185b2ec.png)
The stripes are going to be a problem when the resolution gets lower though (This is 180x180 and it is probably going to be the highest version)

Here is 120x120. Not good.
![irhm-icon-smaller](https://cloud.githubusercontent.com/assets/728801/9717366/78efb010-5572-11e5-850b-a45305eae45d.png)
I'll have to use a different approach for the small ones.

**Comment by QuentinRoy** [comment]
Smooth versions. Much better for the small one. Maybe also better for the big one. Maybe we do not even want the gradient.
![irhm-icon-smooth](https://cloud.githubusercontent.com/assets/728801/9717494/88b9b4b8-5573-11e5-94b0-db433077a31a.png)
![irhm-icon-smooth-small](https://cloud.githubusercontent.com/assets/728801/9717496/8a5a4792-5573-11e5-9b60-e1e89c8ba742.png)

**Comment by QuentinRoy** [comment]
Other approaches to see what it looks like. Pick your side.
![irhm-icon-simple](https://cloud.githubusercontent.com/assets/728801/9717678/fd1a119e-5574-11e5-849c-dab9f23f127f.png)
![irhm-icon-simple](https://cloud.githubusercontent.com/assets/728801/9717787/c2c1f66e-5575-11e5-9a36-9c0153d5dcc4.png)
![irhm-icon-simple](https://cloud.githubusercontent.com/assets/728801/9717828/28676080-5576-11e5-9659-2ae5cec2e7f7.png)

**Comment by almet** [comment]
Hmm,the first one of the last series?

**Comment by phrawzty** [comment]
Of the three above, I prefer the [second one](https://cloud.githubusercontent.com/assets/728801/9717787/c2c1f66e-5575-11e5-9a36-9c0153d5dcc4.png), mostly because fine gradients can be problematic in print (I concede that this may not be a concern).

All three have a very Helvetica feel to them, which is a good thing, though I'd be interested in seeing what a serif-style symbol might look like too. :smile:

**Comment by QuentinRoy** [comment]
Wow. I am both flattered that you thought I could be able to do that and sorry to have to tell you that I am clearly not! I can do rectangle, circle and stuff, but when it comes to curve, we'll need a real graphic designer.
Yes you are right flat is much more today. Though in this case I think I prefer reversed. Here are other attempts.
Inversed.
![irhm-icon-reverse](https://cloud.githubusercontent.com/assets/728801/9719621/5805cc4a-5586-11e5-91a5-653e714166c5.png)
With slight gradient. Maybe too slight.
![irhm-icon-reverse-gradient](https://cloud.githubusercontent.com/assets/728801/9719625/5cca2208-5586-11e5-9498-b406c443a809.png)
Errrrh.. Why not. I guess.. Probably not.
![irhm-icon-border](https://cloud.githubusercontent.com/assets/728801/9719632/6a3bf524-5586-11e5-864b-6cef2b88d56a.png)
Darker, H a bit more colorful (with gradient).
![irhm-icon-reverse-more-gradient](https://cloud.githubusercontent.com/assets/728801/9719876/ecce3f90-5588-11e5-882e-537aa37933b7.png)

**Comment by leplatrem** [comment]
I like the first flat one. Maybe the two vertical bars are a bit too close #dunno

**Comment by QuentinRoy** [comment]
A bit more space between the strokes (square in the middle). Flat vertical lines. No gradient. Top stroke a bit greener.
![irhm-icon-new](https://cloud.githubusercontent.com/assets/728801/9720030/76168108-558a-11e5-80b2-a0759bafd26a.png)
I tried other stuffs with different colours for the bars.
![irhm-icon-5](https://cloud.githubusercontent.com/assets/728801/9720277/f21ea3b4-558c-11e5-979d-d384585aa20e.png)
![irhm-icon-2](https://cloud.githubusercontent.com/assets/728801/9720073/13081904-558b-11e5-8fc1-2d4fd2b11e68.png)
![irhm-icon-3](https://cloud.githubusercontent.com/assets/728801/9720154/c6710104-558b-11e5-960a-6868887aefc6.png)
![irhm-icon-4](https://cloud.githubusercontent.com/assets/728801/9720177/23020ff8-558c-11e5-92d4-8d3e007cda01.png)
(this one start to go a bit away from the currency idea I had at the beginning)
With horizontal strokes aligned on the right
![irhm-icon-better](https://cloud.githubusercontent.com/assets/728801/9720384/d4e5b6ec-558d-11e5-85a0-71a53f511529.png)

**Comment by phrawzty** [comment]
I like the tinted bar aspect of [the first one above](https://cloud.githubusercontent.com/assets/728801/9720030/76168108-558a-11e5-80b2-a0759bafd26a.png). Just enough of a highlight to be interesting but not so much that it's distracting.

**Comment by QuentinRoy** [comment]
I agree. I added a last [variant of it at the end](https://cloud.githubusercontent.com/assets/728801/9720384/d4e5b6ec-558d-11e5-85a0-71a53f511529.png). This is the one that gets my vote.

**Comment by almet** [comment]
I like the last one and this one: ![irhm-icon-5](https://cloud.githubusercontent.com/assets/728801/9720277/f21ea3b4-558c-11e5-979d-d384585aa20e.png)

**Comment by QuentinRoy** [comment]
Here is a mix between the two then. If everybody is OK with it, I will for this one.
![irhm-icon-final](https://cloud.githubusercontent.com/assets/728801/9730204/2a7f9a6e-5615-11e5-9bb8-8fd1e7ed7ce8.png)

**Comment by QuentinRoy** [comment]
Almost forgot my wife thought it would be a bit better if it was less sharp (no pun intended). Now that it's done, I think she may be right. OK with this?
![irhm-icon-last](https://cloud.githubusercontent.com/assets/728801/9729922/423b240e-5613-11e5-859e-50df4ac1b25a.png)

**Comment by almet** [comment]
Haha, "my wife".

My preference goes to [irhm-icon-final](https://cloud.githubusercontent.com/assets/728801/9729590/ac4a72c6-5610-11e5-983f-d034ed849e43.png)

**Comment by almet** [comment]
Oh, or actually the last one, both are nice looking.

**Comment by QuentinRoy** [comment]
Haha ! Yeah it still sounds weird for me too.
OK I also find it hard to decide. I think I have a tiny preference for [the sharp one](https://cloud.githubusercontent.com/assets/728801/9730204/2a7f9a6e-5615-11e5-9bb8-8fd1e7ed7ce8.png). Let's see what the others think.

**Comment by QuentinRoy** [comment]
This one is for @phrawzty.
![irhm-icon-serif](https://cloud.githubusercontent.com/assets/728801/9731578/0359854a-561e-11e5-82e6-a8d6efec51be.png)

**Comment by QuentinRoy** [comment]
Mini-série juste histoire d'expérimenter avec une approche un peu différente. Je pense que je préfère le H blanc mais c'est pas trop mal non plus.
![irhm-icon-diff](https://cloud.githubusercontent.com/assets/728801/9731973/a6707ac0-5620-11e5-8504-1b5b428948f5.png)
![irhm-icon-diff2](https://cloud.githubusercontent.com/assets/728801/9731974/a6862208-5620-11e5-9d78-29d1d6e00065.png)

**Comment by QuentinRoy** [comment]
OK. To stop the flood, after a small discussion with @ametaireau, this one is the final choice for now.
![irhm-icon-final](https://cloud.githubusercontent.com/assets/728801/9732337/6d13bec4-5623-11e5-81df-2130a8a46fd4.png)

**Comment by almet** [comment]
Thanks a lot for the investigation. This rocks :-)
